### ISSUE TITLE
Way to validate if input is actually a YAML

### ISSUE THREAD

**Issue by vmatt** [hunyadi/yaml-to-json#2]
`CHECK_YAML` only return the error message, if the input contains **some** YAML, but it's malformed. However, it silently fails, if we just pass a single string, without any newlines, or tabulation.

## Current behavior
`SELECT CHECK_YAML('"not a valid YAML"');` -> null
`SELECT YAML_TO_JSON('not a valid YAML');` -> `"not a valid YAML"`.  

## Expected behavior
`SELECT CHECK_YAML('"not a valid YAML"');` ->` "ERROR: invalid YAML"`
`SELECT YAML_TO_JSON('not a valid YAML');` -> `null` (maybe `"ERROR: Invalid YAML"` would be better)

**Comment by hunyadi** [comment]
I am not sure I understand. A single quoted string *is* a valid YAML document. By definition, `CHECK_YAML` should return `NULL` only if the input is well-formed, in alignment with Snowflake's own [CHECK_JSON](https://docs.snowflake.com/en/sql-reference/functions/check_json).
